### ISSUE TITLE
URLs for gas fees estimates in Polygon changed

### ISSUE THREAD

**Issue by ramirotw** [enzoferey/network-gas-price#25]
Hey! This morning the urls used to estimate gas fees in Polygon started to fail, according to the docs the urls changed and they dropped the old one:
* old: https://gasstation-mainnet.matic.network/v2
* new: https://gasstation.polygon.technology/v2

**Comment by enzoferey** [comment]
Thanks for the report @ramirotw 🙌🏻 

Updates the urls via https://github.com/enzoferey/network-gas-price/pull/26. Just published version https://github.com/enzoferey/network-gas-price/releases/tag/v0.3.5 to include it 👍🏻

**Comment by enzoferey** [comment]
@ramirotw @smoove There was an breaking change (or bug dunno) on the Polygon station side and they sometimes return string values instead of numbers as stated in their docs. I have made the required changes to cover this anomaly via https://github.com/enzoferey/network-gas-price/releases/tag/v0.3.6.
